VendasOnlineCursoMvc/Models/Departamento.cs
namespace VendasOnlineCursoMvc.Models
{
    public class Departamento
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

VendasOnlineCursoMvc/Models/ErrorViewModel.cs
using System;

namespace VendasOnlineCursoMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VendasOnlineCursoMvc/Models/ViewModels/ErrorViewModel.cs
using System;

namespace VendasOnlineCursoMvc.Models.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VendasOnlineCursoMvc/Controllers/DepartamentoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using VendasOnlineCursoMvc.Models;

namespace VendasOnlineCursoMvc.Controllers
{
    public class DepartamentoController : Controller
    {
        public IActionResult Index()
        {
            List<Departamento> list = new List<Departamento>();
            list.Add(new Departamento { Id = 1, Name = "Eletrônicos" });
            list.Add(new Departamento { Id = 2, Name = "Moda" });
            list.Add(new Departamento { Id = 3, Name = "Móveis" });

            return View(list);
        }
    }
}

VendasOnlineCursoMvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VendasOnlineCursoMvc.Models;

namespace VendasOnlineCursoMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Sobre()
        {
            ViewData["TextoDaPagina"] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a accumsan elit. Cras arcu turpis, rhoncus et interdum tincidunt, sodales ut justo. Vivamus dui lectus, fringilla at tincidunt a, aliquet id metus. Cras non feugiat arcu, at faucibus dui. Morbi accumsan ornare ipsum a sollicitudin. Donec pellentesque ornare hendrerit. Nulla fringilla nisl non dui euismod sollicitudin. Sed nec fermentum sapien. Etiam eu mauris ac magna luctus consequat non eu odio. Morbi non justo eu orci sagittis aliquet vel et arcu. Quisque ultricies dictum tortor quis efficitur";
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new Models.ViewModels.ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VendasOnlineCursoMvc/Views/Departamento/Index.cshtml
@model IEnumerable<VendasOnlineCursoMvc.Models.Departamento>

@{
    ViewData["Title"] = "Departamentos";
}

<h1>Departamentos</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

VendasOnlineCursoMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

VendasOnlineCursoMvc/Views/Home/Index1.cshtml
@page
@model VendasOnlineCursoMvc.Views.Home.Index1Model
@{
}

VendasOnlineCursoMvc/Views/Home/Index2.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

VendasOnlineCursoMvc/Views/Home/Sobre.cshtml
@{
    ViewData["Title"] = "Sobre a Aplicação";
}
<h1>@ViewData["Title"]</h1>
<p>@ViewData["TextoDaPagina"]</p>

VendasOnlineCursoMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VendasOnlineCursoMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VendasOnlineCursoMvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departamento" asp-action="Index">Departamentos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - VendasOnlineCursoMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>